task: detection

num_classes: 2
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /content/coco/images/train2017
    ann_file: /content/coco/annotations/new_instances_train2017_coco_trimmed.json
    # ann_file: /home/kevin/Custom-RT-DETR/rtdetr_pytorch/new1_instances_train2017_coco_trimmed.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 12
  num_workers: 6
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /content/coco/images/val2017
    ann_file: /content/coco/annotations/new_instances_val2017_coco_trimmed.json
    # ann_file: /home/kevin/Custom-RT-DETR/rtdetr_pytorch/new1_instances_val2017_coco_trimmed.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 12
  num_workers: 6
  drop_last: False