__include__: [
  '../dataset/syntetic_fruits.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_yolov8bb_vd.yml',
]

output_dir: ./output/rtdetr_yolov8bb

HybridEncoder:
  expansion: 0.5

RTDETRTransformer:
  eval_idx: 2 # use 3th decoder layer to eval