__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
  './include/backup.yml',
]

output_dir: ./output/rtdetr_r50vd_6x_coco
