__include__: [
  '../dataset/syntetic_fruits.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
  './include/backup.yml',
]

output_dir: ./output/rtdetr_r101vd_6x_cocotrimmed

PResNet:
  depth: 101


HybridEncoder:
  # intra
  hidden_dim: 384
  dim_feedforward: 2048


RTDETRTransformer:
  feat_channels: [384, 384, 384]


optimizer:
  type: AdamW
  params: 
    - 
      params: 'backbone'
      lr: 0.000001