__include__: [
  '../dataset/coco_trimmed.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_cyolov9ebb_vd.yml',
  './include/backup.yml',
]

output_dir: ./output/rtdetr_cyolov9ebb
